---
name: Catalyst-Plugin-AtomPP
version: 0.04
author:
  - Daisuke Murase <typester@cpan.org>
abstract: Dispatch AtomPP methods with Catalyst.
license: perl
requires:
  Catalyst: 5.30
  XML::Atom: 0
provides:
  Catalyst::Plugin::AtomPP:
    file: lib/Catalyst/Plugin/AtomPP.pm
    version: 0.04
generated_by: Module::Build version 0.2611
