---
name: Catalyst-Plugin-AtomPP
version: 0.05_02
author:
  - 'Daisuke Murase, E<lt>typester@cpan.orgE<gt>'
abstract: Dispatch AtomPP methods with Catalyst.
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Catalyst: 5.50
  HTTP::Body: 0.06
  XML::Atom: 0
provides:
  Catalyst::Plugin::AtomPP:
    file: lib/Catalyst/Plugin/AtomPP.pm
    version: 0.05_02
generated_by: Module::Build version 0.2703
